env:
  - PACKAGE_VERSION="1.1.0-rc5"
language: csharp
mono: none
dotnet: 2.1.302
script:
  - dotnet restore
  - dotnet build -c release -o ../bin
after_success:
  - if [ "$TRAVIS_BRANCH" = "master" ]; then
      for nupkg in ./bin/*.nupkg; do
          dotnet nuget push $nupkg -s $NUGET_REGISTRY -k $NUGET_API_KEY;
      done
    fi
